---
# linux_postinstall aliases

- name: "Aliases: Configure /etc/aliases"
  notify: newaliases
  ansible.builtin.template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: "0644"
    backup: "{{ lp_backup_conf }}"

# EOF
