---
# linux_postinstall apt

- name: "Apt: Debug lp_apt_debug={{ lp_apt_debug }}"
  when: lp_apt_debug | bool
  tags: lp_apt_debug
  vars:
    msg: |-
      ansible_os_family: {{ ansible_os_family }}
      lp_apt_conf:
        {{ lp_apt_conf | to_nice_yaml(indent=2) | indent(2) }}
      lp_backup_conf: {{ lp_backup_conf }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Apt: Configure /etc/apt/apt.conf.d"
  notify: "{{ item.notify | d(omit) }}"
  tags: lp_apt_conf
  ansible.builtin.template:
    src: "{{ item.template | d('apt-confd.j2') }}"
    dest: /etc/apt/apt.conf.d/{{ item.file }}
    owner: "{{ item.owner | d('root') }}"
    group: "{{ item.group | d('root') }}"
    mode: "{{ item.mode | d('0644') }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_apt_conf }}"
  loop_control:
    label: "{{ item.file }}"

# EOF
