---
# linux_postinstall bluetooth

- name: "Bluetooth: Debug lp_bluetooth_debug={{ lp_bluetooth_debug }}"
  when: lp_bluetooth_debug | bool
  tags: lp_bluetooth_debug
  vars:
    msg: |-
      ansible_os_family: {{ ansible_os_family }}
      lp_bluetooth_enable: {{ lp_bluetooth_enable }}
      lp_bluetooth_main_conf:
        {{ lp_bluetooth_main_conf | to_yaml(indent=2) | indent(2) }}
      lp_bluetooth_ini:
        {{ lp_bluetooth_ini | to_yaml(indent=2) | indent(2) }}
      lp_backup_conf: {{ lp_backup_conf }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: Configure bluetooth
  notify: restart bluetooth
  block:

    - name: "Bluetooth: Configure /etc/bluetooth/main.conf"
      tags: lp_bluetooth_conf
      ansible.builtin.lineinfile:
        dest: /etc/bluetooth/main.conf
        regexp: ^\s*{{ item.key }}\s*=\s*(.*)$
        insertbefore: ^[\s#]*{{ item.key }}(.*)$
        line: "{{ item.key }} = {{ item.value }}"
        backup: "{{ lp_backup_conf }}"
      loop: "{{ lp_bluetooth_main_conf }}"
      loop_control:
        label: "{{ item.key }} {{ item.value }}"

    - name: "Bluetooth: Configure bluetooth"
      tags: lp_bluetooth_ini
      community.general.ini_file:
        path: "{{ item.0.path }}"
        mode: "{{ item.0.mode }}"
        section: "{{ item.1.section }}"
        option: "{{ item.1.option | d(omit) }}"
        value: "{{ item.1.value }}"
        backup: "{{ lp_backup_conf }}"
      loop: "{{ lp_bluetooth_ini | subelements('conf') }}"
      loop_control:
        label: "{{ item.1.option }}: {{ item.1.value }}"

- name: Service bluetooth
  tags: lp_bluetooth_service
  block:

    - name: "Bluetooth: Service {{ state ~ ' and ' ~ enable }}"
      register: result
      vars:
        enabled: "{{ lp_bluetooth_enable | bool | d(false) }}"
        state: "{{ lp_bluetooth_state | d(default_state) }}"
        default_state: "{{ enabled | ternary('started', 'stopped') }}"
        enable: "{{ enabled | ternary('enabled', 'disabled') }}"
      ansible.builtin.service:
        name: "{{ lp_bluetooth_service }}"
        state: "{{ state }}"
        enabled: "{{ enabled }}"

    - name: "Bluetooth: Debug service lp_bluetooth_debug={{ lp_bluetooth_debug }}"
      when: lp_bluetooth_debug | bool
      ansible.builtin.debug:
        var: result

# EOF
