---
# linux_postinstall debsums

- name: "debsums: Debug"
  vars:
    msg: |-
      ansible_os_family: {{ ansible_os_family }}
      lp_debsums_install: {{ lp_chrony_install }}
      lp_debsums_default_file: {{ lp_debsums_default_file }}
      lp_debsums_default_conf:
        {{ lp_debsums_default_conf|to_yaml(indent=2)|indent(2) }}
      lp_debsums_ignore_file: {{ lp_debsums_ignore_file }}
      lp_debsums_ignore_conf:
        {{ lp_debsums_ignore_conf|to_nice_yaml(indent=2)|indent(2) }}
      lp_debsums_packages:
        {{ lp_debsums_packages|to_nice_yaml(indent=2)|indent(2) }}
      lp_backup_conf: {{ lp_backup_conf }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: lp_debsums_debug|bool
  tags: lp_debsums_debug

- name: "debsums: Install packages"
  ansible.builtin.include_tasks:
    file: fn/install-package.yml
    apply:
      tags: lp_debsums_packages
  loop: "{{ lp_debsums_packages }}"
  when: lp_debsums_install|bool
  tags: lp_debsums_packages

- name: "debsums: Configure {{ lp_debsums_default_file }}"
  ansible.builtin.lineinfile:
    dest: "{{ lp_debsums_default_file }}"
    state: "{{ item.state|default(omit) }}"
    regexp: '^\s*{{ item.key }}\s*=(.*)$'
    line: "{{ item.key }}={{ item.value }}"
    backup: "{{ lp_backup_conf }}"
    create: true
    mode: "0644"
  loop: "{{ lp_debsums_default_conf }}"
  tags: lp_debsums_default_conf

- name: "debsums: Configure {{ lp_debsums_ignore_file }}"
  ansible.builtin.lineinfile:
    dest: "{{ lp_debsums_ignore_file }}"
    state: "{{ item.state|default(omit) }}"
    line: "{{ item }}"
    backup: "{{ lp_backup_conf }}"
    create: true
    mode: "0644"
  loop: "{{ lp_debsums_ignore_conf }}"
  tags: lp_debsums_ignore_conf

# EOF
...
