---
# linux_postinstall libvirt_conf

- name: "libvirt_conf: Debug"
  ansible.builtin.debug:
    msg: "{{ item }}"
  when: lp_libvirt_debug|bool

- name: "libvirt_conf: Configure {{ lp_libvirt_conf_dir }}/{{ item.key }}"
  ansible.builtin.lineinfile:
    create: true
    dest: "{{ lp_libvirt_conf_dir }}/{{ item.key }}"
    regexp: '^\s*{{ conf.0 }}(\s|=)(.*)$'
    line: "{{ conf.0 }} = {{ conf.1 }}"
    state: "{{ conf.2|default('present') }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ item.value }}"
  loop_control:
    loop_var: conf
  notify:
    - reload libvirtd
    - reload libvirt_guests

# EOF
...
