---
# linux_postinstall ModemManager

- name: "Modemmanager: Configure /etc/init/modemmanager.override"
  ansible.builtin.template:
    src: modem-manager-override.j2
    dest: /etc/init/modemmanager.override
    owner: root
    group: root
    mode: "0644"

- name: "Modemmanager: Service {{ state }} and {{ enable }}"
  ansible.builtin.service:
    name: "{{ lp_modemmanager_service }}"
    state: "{{ state }}"
    enabled: "{{ enabled }}"
  register: result
  vars:
    enabled: "{{ lp_modemmanager_enable | bool | d(false) }}"
    state: "{{ lp_modemmanager_state | d(default_state) }}"
    default_state: "{{ enabled | ternary('started', 'stopped') }}"
    enable: "{{ enabled | ternary('enabled', 'disabled') }}"
  tags: lp_modemmanager_service

- name: "Modemmanager: Debug service"
  ansible.builtin.debug:
    var: result
  when: lp_modemmanager_debug|bool
  tags: lp_modemmanager_service

# EOF
