---
# linux-postinstall ModemManager

- name: "modem_manager: Configure /etc/init/modemmanager.override"
  template:
    src: "modem-manager-override.j2"
    dest: "/etc/init/modemmanager.override"
    owner: "root"
    group: "root"
    mode: "0644"
  
- name: "modem_manager: Stop and disable ModemManager"
  service:
    name: "ModemManager"
    state: "stopped"
    enabled: no
  when: not lp_modemmanager

- name: "modem_manager: Start and enable ModemManager"
  service:
    name: "ModemManager"
    state: "started"
    enabled: yes
  when: lp_modemmanager

# EOF
...
