---
# linux_postinstall packages

- name: "packages: Instantiate dynamic variables"
  set_fact:
    my_packages_install: "{{ my_packages_install }}"
    my_packages_lists: "{{ my_packages_lists }}"
    my_packages_auto: "{{ my_packages_auto }}"
  tags:
    - lp_packages_debug
    - lp_packages_auto

- name: "packages: Debug (lp_packages_debug={{ lp_packages_debug }})"
  vars:
    msg: |-
      ansible_os_family: {{ ansible_os_family }}
      lp_packages_auto: {{ lp_packages_auto }}
      lp_package_state: {{ lp_package_state }}
      lp_packages_autoremove: {{ lp_packages_autoremove|bool }}
      lp_packages_rescue_end_host: {{ lp_packages_rescue_end_host|bool }}

      lp_packages_selections_preinstall:
        {{ lp_packages_selections_preinstall|to_yaml(indent=2)|indent(2) }}
      lp_packages_install:
        {{ lp_packages_install|to_nice_yaml(indent=2)|indent(2) }}
      lp_packages_remove:
        {{ lp_packages_remove|to_nice_yaml(indent=2)|indent(2) }}
      lp_packages_selections_postinstall:
        {{ lp_packages_selections_postinstall|to_nice_yaml(indent=2)|indent(2) }}
      my_packages_install:
        {{ my_packages_install|to_yaml(indent=2)|indent(2) }}
      my_packages_lists:
        {{ my_packages_lists|to_yaml(indent=2)|indent(2) }}
      my_packages_auto:
        {{ my_packages_auto|to_yaml(indent=2)|indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: lp_packages_debug|bool
  tags: lp_packages_debug

- name: "packages: Auto install"
  ansible.builtin.import_role:
    name: vbotka.linux_lib
    tasks_from: install_package.yml
  vars:
    ll_ipkg_list: "{{ my_packages_auto|flatten|unique }}"
    ll_ipkg_state: "{{ lp_package_state }}"
    ll_ipkg_autoremove: "{{ lp_packages_autoremove|bool }}"
    ll_ipkg_rescue_end_host: "{{ lp_packages_rescue_end_host|bool }}"
    ll_debug: "{{ lp_packages_debug|bool }}"
  when:
    - lp_packages_auto|bool
    - my_packages_auto|flatten|length > 0
  tags: lp_packages_auto

- name: "packages: Install"
  ansible.builtin.import_role:
    name: vbotka.linux_lib
    tasks_from: install_package.yml
  vars:
    ll_ipkg_list: "{{ lp_packages_install }}"
    ll_ipkg_state: "{{ lp_package_state }}"
    ll_ipkg_autoremove: "{{ lp_packages_autoremove|bool }}"
    ll_ipkg_rescue_end_host: "{{ lp_packages_rescue_end_host|bool }}"
    ll_debug: "{{ lp_packages_debug|bool }}"
  when: lp_packages_install|length > 0
  tags: lp_packages_install

- name: "packages: Remove"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ lp_package_state_remove }}"
  loop: "{{ lp_packages_remove }}"
  register: result
  retries: "{{ lp_install_retries }}"
  delay: "{{ lp_install_delay }}"
  until: result is succeeded
  tags: lp_packages_remove

- name: "packages: Debug result"
  ansible.builtin.debug:
    var: result
  when: lp_packages_debug|bool
  tags: lp_packages_remove

# EOF
...
