---
# linux_postinstall speechd

- name: "Speechd: Debug lp_speechd_debug={{ lp_speechd_debug }}"
  when: lp_speechd_debug | bool
  ansible.builtin.debug:
    msg: "lp_speechd_enable: {{ lp_speechd_enable }}"

- name: Service speechd
  tags: lp_speechd_service
  block:

    - name: "Speechd: Service {{ state ~ ' and ' ~ enable }}"
      register: result
      vars:
        enabled: "{{ lp_speechd_enable | bool | d(false) }}"
        state: "{{ lp_speechd_state | d(default_state) }}"
        default_state: "{{ enabled | ternary('started', 'stopped') }}"
        enable: "{{ enabled | ternary('enabled', 'disabled') }}"
      ansible.builtin.service:
        name: "{{ lp_speechd_service }}"
        state: "{{ state }}"
        enabled: "{{ enabled }}"

    - name: "Speechd: Debug service lp_speechd_debug={{ lp_speechd_debug }}"
      when: lp_speechd_debug | bool
      ansible.builtin.debug:
        var: result

# EOF
