---
# linux_postinstall virtualbox

- name: "virtualbox: Debug"
  vars:
    msg: |-
      ansible_lsb.description: {{ ansible_lsb.codename }}
      lp_virtualbox: {{ lp_virtualbox }}
      lp_virtualbox_ignore_errors: {{ lp_virtualbox_ignore_errors }}
      lp_virtualbox_keys: {{ lp_virtualbox_keys }}
      lp_virtualbox_repos: {{ lp_virtualbox_repos }}
      lp_virtualbox_packages:
        {{ lp_virtualbox_packages|to_nice_yaml(indent=2)|indent(2) }}
      lp_virtualbox_services:
        {{ lp_virtualbox_services|to_nice_yaml(indent=2)|indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: lp_virtualbox_debug|bool
  tags: lp_virtualbox_debug

# TODO: assert lp_virtualbox_modules are loaded
#       when: lp_virtualbox|bool

- name: "virtualbox: Add signing key of VirtualBox"
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ lp_virtualbox_keys }}"
  register: result
  retries: "{{ lp_install_retries }}"
  until: result is succeeded
  delay: "{{ lp_install_delay }}"
  ignore_errors: "{{ lp_virtualbox_ignore_errors }}"  # noqa ignore-errors
  tags: lp_virtualbox_keys

- name: "virtualbox: Add repository of VirtualBox"
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ lp_virtualbox_repos }}"
  ignore_errors: "{{ lp_virtualbox_ignore_errors }}"  # noqa ignore-errors
  tags: lp_virtualbox_repos

- name: "virtualbox: Install VirtualBox packages"
  ansible.builtin.include_tasks:
    file: fn/install-package.yml
    apply:
      tags: lp_virtualbox_packages
  loop: "{{ lp_virtualbox_packages }}"
  ignore_errors: "{{ lp_virtualbox_ignore_errors }}"  # noqa ignore-errors
  when: lp_virtualbox_install|bool
  tags: lp_virtualbox_packages

- name: "virtualbox: Services start/stop and enable/disable"
  ansible.builtin.service:
    name: "{{ srv_name }}"
    state: "{{ srv_stat }}"
    enabled: "{{ srv_enbl }}"
  loop: "{{ lp_virtualbox_services }}"
  loop_control:
    label: "{{ srv_name }} state: {{ srv_stat }} enabled: {{ srv_enbl }}"
  vars:
    srv_name: "{{ lookup('vars', 'lp_' ~ item ~ '_service', default=item) }}"
    srv_enbl: "{{ lookup('vars', 'lp_' ~ item ~ '_enable', default=false) }}"
    srv_stat: "{{ lookup('vars', 'lp_' ~ item ~ '_state', default=default_stat) }}"
    default_stat: "{{ srv_enbl|bool|ternary('started', 'stopped') }}"
  tags: lp_virtualbox_service

# EOF
...
