---
# linux_postinstall wpasupplicant

- name: "wpasupplicant: Debug"
  vars:
    msg: |-
      lp_package_state: {{ lp_package_state }}
      lp_wpasupplicant_install: {{ lp_wpasupplicant_install }}
      lp_wpasupplicant_packages:
        {{ lp_wpasupplicant_packages|to_nice_yaml|indent(2) }}
      lp_wpasupplicant_bin: {{ lp_wpasupplicant_bin }}
      lp_wpasupplicant_conf_only: {{ lp_wpasupplicant_conf_only }}
      lp_wpasupplicant_conf_dir: {{ lp_wpasupplicant_conf_dir }}
      lp_wpasupplicant_conf_owner: {{ lp_wpasupplicant_conf_owner }}
      lp_wpasupplicant_conf_group: {{ lp_wpasupplicant_conf_group }}
      lp_wpasupplicant_conf_mode: {{ lp_wpasupplicant_conf_mode }}
      lp_wpasupplicant_conf_ctrl_interface: {{ lp_wpasupplicant_conf_ctrl_interface }}
      lp_wpasupplicant_conf_global:
        {{ lp_wpasupplicant_conf_global|to_yaml|indent(2) }}
      lp_wpa_action_script: {{ lp_wpa_action_script }}
      lp_wpa_action_script_dir: {{ lp_wpa_action_script_dir }}
      lp_wpa_action_script_dir_owner: {{ lp_wpa_action_script_dir_owner }}
      lp_wpa_action_script_dir_group: {{ lp_wpa_action_script_dir_group }}
      lp_wpa_action_script_dir_mode: {{ lp_wpa_action_script_dir_mode }}
      lp_wpa_action_script_file: {{ lp_wpa_action_script_file }}
      lp_wpa_action_script_owner: {{ lp_wpa_action_script_owner }}
      lp_wpa_action_script_group: {{ lp_wpa_action_script_group }}
      lp_wpa_action_script_mode: {{ lp_wpa_action_script_mode }}
      lp_wpa_action_script_dhclient: {{ lp_wpa_action_script_dhclient }}
      lp_wpa_action_script_pidfile: {{ lp_wpa_action_script_pidfile }}
      lp_wpa_action_script_options_connect: {{ lp_wpa_action_script_options_connect }}
      lp_wpa_action_script_options_disconnect: {{ lp_wpa_action_script_options_disconnect }}
      lp_wpa_action_script_logfile: {{ lp_wpa_action_script_logfile }}
      lp_wpasupplicant_service_conf:
        {{ lp_wpasupplicant_service_conf|to_yaml|indent(2) }}
      {% if lp_wpasupplicant_debug_classified|bool %}
      lp_wpasupplicant_conf:
        {{ lp_wpasupplicant_conf|to_yaml|indent(2) }}
      {% endif %}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: lp_wpasupplicant_debug|bool
  tags: lp_wpasupplicant_debug

# Packages
- name: "wpasupplicant: Install packages"
  ansible.builtin.include_tasks: fn/install-package.yml
  loop: "{{ lp_wpasupplicant_packages }}"
  when: lp_wpasupplicant_install|bool
  tags: lp_wpasupplicant_packages

# Action script for wpa_cli
- name: "wpasupplicant: Create dir {{ lp_wpa_action_script_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ lp_wpa_action_script_dir }}"
    owner: "{{ lp_wpa_action_script_dir_owner }}"
    group: "{{ lp_wpa_action_script_dir_group }}"
    mode: "{{ lp_wpa_action_script_dir_mode }}"
  when: lp_wpa_action_script|bool
  tags: lp_wpa_action_script_dir

- name: "wpasupplicant: Create script {{ lp_wpa_action_script_file }}"
  ansible.builtin.template:
    src: wpa_action.sh.j2
    dest: "{{ lp_wpa_action_script_file }}"
    owner: "{{ lp_wpa_action_script_owner }}"
    group: "{{ lp_wpa_action_script_group }}"
    mode: "{{ lp_wpa_action_script_mode }}"
    backup: "{{ lp_backup_conf }}"
  when: lp_wpa_action_script|bool
  tags: lp_wpa_action_script

# Conf
- name: "wpasupplicant: Create wpasupplicant configuration"
  ansible.builtin.template:
    src: wpa_supplicant.conf.j2
    dest: "{{ lp_wpasupplicant_conf_dir }}/{{ my_filename }}"
    owner: "{{ lp_wpasupplicant_conf_owner }}"
    group: "{{ lp_wpasupplicant_conf_group }}"
    mode: "{{ lp_wpasupplicant_conf_mode }}"
    backup: "{{ lp_backup_conf }}"
  register: lp_wpasupplicant_conf_changes
  notify: reconfigure wpa_supplicant
  loop: "{{ lp_wpasupplicant_conf }}"
  loop_control:
    label: "{{ my_filename }}"
  no_log: "{{ not lp_wpasupplicant_debug_classified }}"
  vars:
    my_filename: "{{ lp_wpasupplicant_conf_file[item.type|default('default')] }}"
  tags: lp_wpasupplicant_conf

- name: "wpasupplicant: Debug: Create wpasupplicant configuration"
  ansible.builtin.debug:
    var: lp_wpasupplicant_conf_changes
  when: lp_wpasupplicant_debug_classified|bool
  tags: lp_wpasupplicant_conf

# Service
- name: "wpasupplicant: Configure wpa_supplicant services"
  community.general.ini_file:
    path: "{{ item.0.path }}/{{ item.0.service }}"
    owner: "{{ item.0.owner|default(omit) }}"
    group: "{{ item.0.group|default(omit) }}"
    mode: "{{ item.0.mode|default(omit) }}"
    create: "{{ item.0.create|default(omit) }}"
    no_extra_spaces: "{{ item.0.no_extra_spaces|default(omit) }}"
    section: "{{ item.1.section }}"
    state: "{{ item.1.state|default(omit) }}"
    option: "{{ item.1.option|default(omit) }}"
    value: "{{ item.1.value|default(omit) }}"
    backup: "{{ lp_backup_conf }}"
  register: lp_wpasupplicant_service_conf_changes
  notify: "{{ item.0.handlers|default(omit) }}"  # TODO: see handlers
  loop: "{{ lp_wpasupplicant_service_conf|subelements('ini', {'skip_missing': True}) }}"
  loop_control:
    label: "{{ item.0.path }}/{{ item.0.service }}"
  tags: lp_wpasupplicant_service_conf

- name: "wpasupplicant: Debug: Configure wpasupplicant services"
  ansible.builtin.debug:
    var: lp_wpasupplicant_service_conf_changes
  when: lp_wpasupplicant_debug|bool
  tags: lp_wpasupplicant_service_conf

- name: "wpasupplicant: Manage wpa_supplicant services"
  ansible.builtin.service:
    name: "{{ my_service }}"
    state: "{{ item.state|default('started') }}"
    enabled: "{{ item.enabled|default(true) }}"
    arguments: "{{ item.arguments|default(omit) }}"
    pattern: "{{ item.pattern|default(omit) }}"
    runlevel: "{{ item.runlevel|default(omit) }}"
    sleep: "{{ item.sleep|default(omit) }}"
    use: "{{ item.use|default(omit) }}"
  register: lp_wpasupplicant_service_changes
  loop: "{{ lp_wpasupplicant_conf }}"
  loop_control:
    label: "{{ my_service }}"
  vars:
    my_dev: "{{ item.dev }}"
    my_service: "{{ lp_wpasupplicant_service[item.type|default('default')] }}"
  tags: lp_wpasupplicant_service

- name: "wpasupplicant: Debug: Manage wpa_supplicant services"
  ansible.builtin.debug:
    var: lp_wpasupplicant_service_changes
  when: lp_wpasupplicant_debug_classified|bool
  tags: lp_wpasupplicant_service

# EOF
...
