---
# linux_postinstall xorg

- name: "Xorg: Debug lp_xorg_debug={{ lp_xorg_debug }}"
  when: lp_xorg_debug | bool
  tags: lp_xorg_debug
  vars:
    msg: |-
      lp_xorg_conf:
        {{ lp_xorg_conf | to_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

- name: "Xorg: Configure {{ lp_xorg_conf_dir }}"
  tags: lp_xorg_conf
  ansible.builtin.template:
    src: xorg.conf.j2
    dest: "{{ lp_xorg_conf_dir }}/{{ item.file }}"
    backup: "{{ lp_backup_conf }}"
    mode: "0644"
  loop: "{{ lp_xorg_conf }}"
  loop_control:
    label: "{{ item.file }}"

# EOF
