---

task_systemd_synopsis: |
  Configure systemd.

task_systemd_description: |
  Set my_services (13)
  ^^^^^^^^^^^^^^^^^^^^
  Iterate ``lp_systemd_unit`` (18) and create dictionary
  ``my_services``. It will be used by handlers to decide if and
  how to reload or restart services

  .. code-block:: yaml

     my_services:
       <name>.<type|default(lp_systemd_unit_type)>:
         state: <control.state|default('started')>
         restart_or_reload: <control.restart_or_reload|default('reload')>
     ...

  Debug (31)
  ^^^^^^^^^^
  To see the values of the variables run the playbook with
  options ``-t lp_systemd_debug -e lp_systemd_debug=True`` (54).

  Packages (58)
  ^^^^^^^^^^^^^
  Install packages when enabled (64).

  Configure systemd (68)
  ^^^^^^^^^^^^^^^^^^^^^^

  Use ``community.general.ini_file`` (69) to configure files (70) in loop
  ``with_subelements`` (80-82). Register
  ``lp_systemd_conf_changes`` (79) and notify handler ``reload
  systemd conf`` (85).

  .. code-block:: yaml

     lp_systemd_conf:
       <path>:
         owner: <owner|default(lp_systemd_owner)>
         group: <group|default(lp_systemd_group)>
         mode: <mode|default(lp_systemd_mode)>
         reload_service: <service to be reloaded or restarted by handler>
         conf:
           - {section: <section>, key: <option>, val: <value>}
       ...

  Create units (110)
  ^^^^^^^^^^^^^^^^^^

  Use `` ansible.builtin.template`` (111) to create units in the loop
  (119) when ``state == 'create'`` (123). Register
  ``lp_systemd_unit_create_changes`` (118) and notify handler ``reload
  systemd units`` (122).

  .. code-block:: yaml

     lp_systemd_unit:
       - name: <name of the service>
         type: <type of the service|default(lp_systemd_unit_type)>
         path: <directory of the units|default(lp_systemd_unit_dir)>
         owner: <owner|default(lp_systemd_owner)>
         group: <group|default(lp_systemd_group)>
         mode: <mode|default(lp_systemd_mode)>
         state: <'create' or 'absent'|default('noop')>
       ...

  Remove units (132)
  ^^^^^^^^^^^^^^^^^^

  <TBD>

  Control units (149)
  ^^^^^^^^^^^^^^^^^^^

  .. code-block:: yaml

     lp_systemd_unit:
       - name: <name of the service>
         type: <type of the service|default(lp_systemd_unit_type)>
         control:
           daemon_reexec: <daemon_reexec|default(omit)>
           daemon_reload: <daemon_reload|default(omit)>
           enabled: <enabled|default(systemd_units_enabled)>
           force: <force|default(omit)>
           masked: <masked|default(omit)>
           no_block: <no_block|default(omit)>
           scope: <scope|default(omit)>
           state: <state|default(omit)>


  .. seealso::

     * Description of Parameters `Ansible module systemd
       <https://docs.ansible.com/ansible/latest/modules/systemd_module.html#systemd-manage-services>`_

  <TBD>

task_systemd_lines: 1,2,13,18,31,54,58,64,64,68,70,80-82,79,85,110,111,118,119,122,123,132,149
...
