---

- name: reload acpid
  ansible.builtin.service:
    name: "{{ lp_acpi_service }}"
    state: reloaded
  when: lp_acpi_enable|bool

- name: restart acpid
  ansible.builtin.service:
    name: "{{ lp_acpi_service }}"
    state: restarted
  when: lp_acpi_enable|bool

# EOF
...
