---

- name: apparmor disable profile
  command: apparmor_parser -R /etc/apparmor.d/"{{ apparmor_item_path.stdout }}"

- name: apparmor enforce profile
  command: apparmor_parser -r /etc/apparmor.d/"{{ apparmor_item_path.stdout }}"

# EOF
...
