---

- name: apparmor disable profile
  ansible.builtin.command:
    cmd: >
      apparmor_parser -R /etc/apparmor.d/{{ apparmor_item_path.stdout }}

- name: apparmor enforce profile
  ansible.builtin.command:
    cmd: >
      apparmor_parser -r /etc/apparmor.d/{{ apparmor_item_path.stdout }}

# EOF
...
