---

- name: start chrony
  ansible.builtin.service:
    name: "{{ lp_chrony_service }}"
    state: started

- name: stop chrony
  ansible.builtin.service:
    name: "{{ lp_chrony_service }}"
    state: stopped

- name: restart chrony
  ansible.builtin.service:
    name: "{{ lp_chrony_service }}"
    state: restarted
  when: lp_chrony_enable|bool

# EOF
...
