---
- name: Restart libvirtd
  ansible.builtin.service:
    name: "{{ lp_libvirt_libvirtd_service }}"
    state: restarted
  when: lp_libvirt_libvirtd_enable|bool

- name: Reload libvirtd
  ansible.builtin.service:
    name: "{{ lp_libvirt_libvirtd_service }}"
    state: reloaded
  when: lp_libvirt_libvirtd_enable|bool

- name: Restart libvirt_guests
  ansible.builtin.service:
    name: "{{ lp_libvirt_guests_service }}"
    state: restarted
  when: lp_libvirt_libvirtd_enable|bool

- name: Reload libvirt_guests
  ansible.builtin.service:
    name: "{{ lp_libvirt_guests_service }}"
    state: reloaded
  when: lp_libvirt_libvirtd_enable|bool

# EOF
