---

- name: restart smart
  systemd: name="{{ lp_smart_service }}" state="restarted"
  when: lp_smart_enable|bool

- name: reload smart
  systemd: name="{{ lp_smart_service }}" state="reloaded"
  when: lp_smart_enable|bool

# EOF
...
