---
- name: Reload sshd
  ansible.builtin.service:
    name: "{{ lp_sshd_service }}"
    state: reloaded
  when: lp_sshd_enable|bool

- name: Restart sshd
  ansible.builtin.service:
    name: "{{ lp_sshd_service }}"
    state: restarted
  when: lp_sshd_enable|bool

# EOF
