---

- name: restart timesyncd
  ansible.builtin.service:
    name: "{{ lp_timesyncd_service }}"
    state: restarted
  when:
    - lp_timesyncd_enable | bool
    - lp_timesyncd_service_exists | bool

# EOF
...
