---
- name: Start tlp
  ansible.builtin.service:
    name: "{{ lp_tlp_restart_service }}"
    state: started

- name: Stop tlp
  ansible.builtin.service:
    name: "{{ lp_tlp_restart_service }}"
    state: stopped

- name: Restart tlp
  ansible.builtin.shell:
    cmd: >
      sh -c
      '{{ lp_tlp_path }} init stop &&
      {{ lp_tlp_path }} init start'
  when: lp_tlp_enable|bool

# [TODO] "restarted" freeze 20.04
# systemd: name="{{ lp_tlp_restart_service }}" state=restarted

# EOF
