---
# linux_postinstall function service-systemd

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html#notes
# Quoting from Notes: The order of execution when having multiple
# properties is to first enable/disable, then mask/unmask and then
# deal with service state. It has been reported that systemctl can
# behave differently depending on the order of operations if you do
# the same manually.

- name: Service systemd
  module_defaults:
    ansible.builtin.systemd:
      name: "{{ item.name | d(omit) }}"
      daemon_reexec: "{{ item.daemon_reexec | d(omit) }}"
      daemon_reload: "{{ item.daemon_reload | d(omit) }}"
      enabled: "{{ item.enabled | d(omit) }}"
      force: "{{ item.force | d(omit) }}"
      masked: "{{ item.masked | d(omit) }}"
      no_block: "{{ item.no_block | d(omit) }}"
      scope: "{{ item.scope | d(omit) }}"
      state: "{{ item.state | d(omit) }}"
  vars:
    _enabld: "{{ lp_service | selectattr('enabled', 'defined') | community.general.remove_keys(target=['masked', 'state']) }}"
    _masked: "{{ lp_service | selectattr('masked', 'defined') | community.general.remove_keys(target=['state']) }}"
    enabled: "{{ item.enabled | d('UNDEFINED') }}"
    masked: "{{ item.masked | d('UNDEFINED') }}"
    state: "{{ item.state | d('UNDEFINED') }}"
  block:

    - name: "Service:systemd: enable/disable"
      register: result
      notify: reload systemd daemon
      ansible.builtin.systemd:
      loop: "{{ _enabld }}"
      loop_control:
        label: "{{ item.name }} enabled={{ enabled }}"

    - name: "Service:systemd: Debug"
      when: _enabld | length > 0
      ansible.builtin.include_tasks: fn/service-debug.yml

    - name: "Service:systemd: Flush handlers"
      when: _enabld | length > 0
      ansible.builtin.meta: flush_handlers

    - name: "Service:systemd: mask/unmask"
      register: result
      notify: reload systemd daemon
      ansible.builtin.systemd:
      loop: "{{ _masked }}"
      loop_control:
        label: "{{ item.name }} enabled={{ enabled }} masked={{ masked }}"

    - name: "Service:systemd: Debug"
      when: _masked | length > 0
      ansible.builtin.include_tasks: fn/service-debug.yml

    - name: "Service:systemd: Flush handlers"
      when: _masked | length > 0
      ansible.builtin.meta: flush_handlers

    - name: "Service:systemd: all"
      register: result
      notify: reload systemd daemon
      ansible.builtin.systemd:
      loop: "{{ lp_service }}"
      loop_control:
        label: "{{ item.name }} enabled={{ enabled }} masked={{ masked }} state={{ state }}"

    - name: "Service:systemd: Debug"
      when: lp_service | length > 0
      ansible.builtin.include_tasks: fn/service-debug.yml

# EOF
