---
lp_sshd: true
lp_sshd_enable: true
lp_sshd_pubkeyauthentication: "yes"
lp_sshd_passwordauthentication: "no"
lp_sshd_challengeresponseauthentication: "no"
lp_sshd_permitrootlogin: "yes"
lp_sshd_permittunnel: "no"
lp_sshd_allowtcpforwarding: "yes"
lp_sshd_x11forwarding: "no"
lp_sshd_config:
  - {key: PasswordAuthentication, value: "{{ lp_sshd_passwordauthentication }}"}
  - {key: PubkeyAuthentication, value: "{{ lp_sshd_pubkeyauthentication }}"}
  - {key: ChallengeResponseAuthentication, value: "{{ lp_sshd_challengeresponseauthentication }}"}
  - {key: PermitRootLogin, value: "{{ lp_sshd_permitrootlogin }}"}
  - {key: PermitTunnel, value: "{{ lp_sshd_permittunnel }}"}
  - {key: AllowTcpForwarding, value: "{{ lp_sshd_allowtcpforwarding }}"}
  - {key: X11Forwarding, value: "{{ lp_sshd_x11forwarding }}"}
